# Generated by Django 4.2.29 on 2026-03-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='actors/'),
        ),
        migrations.AddField(
            model_name='play',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plays/'),
        ),
    ]
