# Generated by Django 4.2.29 on 2026-03-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0002_actor_photo_play_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theatrehall',
            name='seats_in_row',
            field=models.CharField(help_text='Number of seats per row (single number for all rows or comma-separated list for each row).', max_length=255),
        ),
    ]
